server:
  port: 9445
  servlet:
    context-path: /item

spring:
  application:
    name: MA-ITEM-SERVICE

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8787/eureka
